package com.duodev.placeholder;

public enum PlayerAnimationType {
    IDLE_STARTUP_DOWN, IDLE_DOWN, IDLE_STARTUP_RIGHT, IDLE_RIGHT,IDLE_STARTUP_UP, IDLE_UP, IDLE_STARTUP_LEFT, IDLE_LEFT, RUNNING_RIGHT, RUNNING_DOWN, RUNNING_LEFT, RUNNING_UP
}